### ISSUE TITLE
Fix TOML Parse Error: Replace `__VERSION__` Placeholder in pyproject.toml with Dynamic Substitution After Checkout

### ISSUE THREAD

**Issue by nkbud** [nkbud/mcp-server-attom#23]
### Problem
The workflow is failing due to a TOML parse error in `pyproject.toml` at line 7:

```toml
version = "__VERSION__"
```

**Cause:** The TOML spec requires the `version` value to start with a number (e.g., `1.0.0`). Placeholders like `__VERSION__` are invalid and cause the parse error.

### Solution
- Replace `__VERSION__` with an actual version number before TOML parsing occurs.
- If dynamic substitution is desired, use a pre-build script or workflow step to perform the replacement immediately after the repository is checked out in your CI pipeline.

**Example workflow addition (e.g., in `.github/workflows/release.yml`):**
```yaml
steps:
  - name: Checkout repository
    uses: actions/checkout@v4
  - name: Set version dynamically
    run: sed -i 's/__VERSION__/1.0.0/' pyproject.toml
    # Optionally, set 1.0.0 to your release version variable
```

### Next Steps
1. Update the workflow to include a dynamic substitution step right after checkout.
2. Optionally, replace the placeholder in `pyproject.toml` directly with a valid version number if dynamic replacement is not needed.
3. Re-run the workflow to confirm the fix.

Let me know if you need help integrating this fix!
